In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("area_meta.csv")
df = df.drop(columns=["category", "is_percentage", "start_date", "end_date"])

In [37]:
# df["category"].value_counts()

In [38]:
df_out = df.pivot(
    index=["area_id"], 
    columns="variable", 
    values="value"
).reset_index()

df_out.columns.name = None

In [39]:
df_out.shape

(19365, 88)

In [40]:
df_out = df_out.fillna(0)

In [41]:
df_out.tail(5)

,area_id,1 person,10 persons,100 years and older (Total female population),100 years and older (Total male population),11 persons or more,2 persons,3 persons,4 persons,5 persons,...,Short cycle Tertiary education (ISCED 5) (Total female population),Short cycle Tertiary education (ISCED 5) (Total male population),Students (Total female population),Students (Total male population),Unemployed (Total female population),Unemployed (Total male population),Upper secondary education (ISCED 3) (Total female population),Upper secondary education (ISCED 3) (Total male population),Younger than 5 years (Total female population),Younger than 5 years (Total male population)
19360,1-6-93090G191,5.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,2.0,1.0,5.0,0.0,0.0
19361,1-6-93090H000,47.0,0.0,0.0,0.0,0.0,29.0,14.0,12.0,7.0,...,0.0,0.0,8.0,5.0,5.0,8.0,37.0,31.0,6.0,4.0
19362,1-6-93090H012,4.0,0.0,0.0,0.0,0.0,10.0,5.0,6.0,2.0,...,0.0,0.0,3.0,1.0,0.0,0.0,7.0,12.0,3.0,0.0
19363,1-6-93090H063,5.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
19364,1-6-93090H091,7.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,5.0,6.0,1.0,1.0

In [42]:
pd.set_option('display.max_columns', None)
print(df_out.columns.tolist())

['area_id', '1 person', '10 persons', '100 years and older (Total female population)', '100 years and older (Total male population)', '11 persons or more', '2 persons', '3 persons', '4 persons', '5 persons', '6 persons', '7 persons', '8 persons', '9 persons', 'Bachelors or equivalent (ISCED 6) (Total female population)', 'Bachelors or equivalent (ISCED 6) (Total male population)', 'Doctorate or equivalent (ISCED 8) (Total female population)', 'Doctorate or equivalent (ISCED 8) (Total male population)', 'Employed (Total female population)', 'Employed (Total male population)', 'From 10 to 14 years (Total female population)', 'From 10 to 14 years (Total male population)', 'From 15 to 19 years (Total female population)', 'From 15 to 19 years (Total male population)', 'From 20 to 24 years (Total female population)', 'From 20 to 24 years (Total male population)', 'From 25 to 29 years (Total female population)', 'From 25 to 29 years (Total male population)', 'From 30 to 34 years (Total female population)', 'From 30 to 34 years (Total male population)', 'From 35 to 39 years (Total female population)', 'From 35 to 39 years (Total male population)', 'From 40 to 44 years (Total female population)', 'From 40 to 44 years (Total male population)', 'From 45 to 49 years (Total female population)', 'From 45 to 49 years (Total male population)', 'From 5 to 9 years (Total female population)', 'From 5 to 9 years (Total male population)', 'From 50 to 54 years (Total female population)', 'From 50 to 54 years (Total male population)', 'From 55 to 59 years (Total female population)', 'From 55 to 59 years (Total male population)', 'From 60 to 64 years (Total female population)', 'From 60 to 64 years (Total male population)', 'From 65 to 69 years (Total female population)', 'From 65 to 69 years (Total male population)', 'From 70 to 74 years (Total female population)', 'From 70 to 74 years (Total male population)', 'From 75 to 79 years (Total female population)', 'From 75 to 79 years (Total male population)', 'From 80 to 84 years (Total female population)', 'From 80 to 84 years (Total male population)', 'From 85 to 89 years (Total female population)', 'From 85 to 89 years (Total male population)', 'From 90 to 94 years (Total female population)', 'From 90 to 94 years (Total male population)', 'From 95 to 99 years (Total female population)', 'From 95 to 99 years (Total male population)', 'Lower secondary education (ISCED 2) (Total female population)', 'Lower secondary education (ISCED 2) (Total male population)', 'Masters or equivalent (ISCED 7) (Total female population)', 'Masters or equivalent (ISCED 7) (Total male population)', 'No diploma or certificate (ISCED 0) (Total female population)', 'No diploma or certificate (ISCED 0) (Total male population)', 'Not applicable (for persons younger than 15) (Total female population)', 'Not applicable (for persons younger than 15) (Total male population)', 'Not specified (for persons 15 years or older) (Total female population)', 'Not specified (for persons 15 years or older) (Total male population)', 'Others (Total female population)', 'Others (Total male population)', 'Pensioners or recipients of capital income (Total female population)', 'Pensioners or recipients of capital income (Total male population)', 'Persons under the national minimum age for economic activity (Total female population)', 'Persons under the national minimum age for economic activity (Total male population)', 'Post-secondary non tertiary education (ISCED 4) (Total female population)', 'Post-secondary non tertiary education (ISCED 4) (Total male population)', 'Primary education (ISCED 1) (Total female population)', 'Primary education (ISCED 1) (Total male population)', 'Short cycle Tertiary education (ISCED 5) (Total female population)', 'Short cycle Tertiary education (ISCED 5) (Total male population)', 'Students (Total female population)', 'Students (Total male population)', 'Unemployed (Total female population)', 'Unemployed (Total male population)', 'Upper secondary education (ISCED 3) (Total female population)', 'Upper secondary education (ISCED 3) (Total male population)', 'Younger than 5 years (Total female population)', 'Younger than 5 years (Total male population)']

In [43]:
df_out['total_male_population'] = df_out['Younger than 5 years (Total male population)'] + df_out['From 5 to 9 years (Total male population)'] + df_out['From 10 to 14 years (Total male population)'] + df_out['From 15 to 19 years (Total male population)']+ df_out['From 20 to 24 years (Total male population)'] + df_out['From 25 to 29 years (Total male population)'] + df_out['From 30 to 34 years (Total male population)'] + df_out['From 35 to 39 years (Total male population)'] + df_out['From 40 to 44 years (Total male population)'] + df_out['From 45 to 49 years (Total male population)'] + df_out['From 50 to 54 years (Total male population)']+ df_out['From 55 to 59 years (Total male population)'] + df_out['From 60 to 64 years (Total male population)'] + df_out['From 65 to 69 years (Total male population)'] + df_out['From 70 to 74 years (Total male population)'] + df_out['From 75 to 79 years (Total male population)'] + df_out['From 80 to 84 years (Total male population)'] + df_out['From 85 to 89 years (Total male population)'] + df_out['From 90 to 94 years (Total male population)'] + df_out['From 95 to 99 years (Total male population)']+ df_out['100 years and older (Total male population)']
df_out['total_female_population'] = df_out['Younger than 5 years (Total female population)'] + df_out['From 5 to 9 years (Total female population)'] + df_out['From 10 to 14 years (Total female population)'] + df_out['From 15 to 19 years (Total female population)']+ df_out['From 20 to 24 years (Total female population)'] + df_out['From 25 to 29 years (Total female population)'] + df_out['From 30 to 34 years (Total female population)'] + df_out['From 35 to 39 years (Total female population)'] + df_out['From 40 to 44 years (Total female population)'] + df_out['From 45 to 49 years (Total female population)'] + df_out['From 50 to 54 years (Total female population)']+ df_out['From 55 to 59 years (Total female population)'] + df_out['From 60 to 64 years (Total female population)'] + df_out['From 65 to 69 years (Total female population)'] + df_out['From 70 to 74 years (Total female population)'] + df_out['From 75 to 79 years (Total female population)'] + df_out['From 80 to 84 years (Total female population)'] + df_out['From 85 to 89 years (Total female population)'] + df_out['From 90 to 94 years (Total female population)'] + df_out['From 95 to 99 years (Total female population)']+ df_out['100 years and older (Total female population)']
df_out['total_population'] = df_out['total_male_population'] + df_out['total_female_population']

df_out['20-34 (male)'] = df_out['From 20 to 24 years (Total male population)'] + df_out['From 25 to 29 years (Total male population)'] + df_out['From 30 to 34 years (Total male population)']
df_out['35-54 (male)'] = df_out['From 35 to 39 years (Total male population)'] + df_out['From 40 to 44 years (Total male population)'] + df_out['From 45 to 49 years (Total male population)'] + df_out['From 50 to 54 years (Total male population)']
df_out['55-69 (male)'] = df_out['From 55 to 59 years (Total male population)'] + df_out['From 60 to 64 years (Total male population)'] + df_out['From 65 to 69 years (Total male population)']
df_out['70+ (male)'] = df_out['From 70 to 74 years (Total male population)'] + df_out['From 75 to 79 years (Total male population)'] + df_out['From 80 to 84 years (Total male population)'] + df_out['From 85 to 89 years (Total male population)'] + df_out['From 90 to 94 years (Total male population)'] + df_out['From 95 to 99 years (Total male population)']

df_out['20-34 (female)'] = df_out['From 20 to 24 years (Total female population)'] + df_out['From 25 to 29 years (Total female population)'] + df_out['From 30 to 34 years (Total female population)']
df_out['35-54 (female)'] = df_out['From 35 to 39 years (Total female population)'] + df_out['From 40 to 44 years (Total female population)'] + df_out['From 45 to 49 years (Total female population)'] + df_out['From 50 to 54 years (Total female population)']
df_out['55-69 (female)'] = df_out['From 55 to 59 years (Total female population)'] + df_out['From 60 to 64 years (Total female population)'] + df_out['From 65 to 69 years (Total female population)']
df_out['70+ (female)'] = df_out['From 70 to 74 years (Total female population)'] + df_out['From 75 to 79 years (Total female population)'] + df_out['From 80 to 84 years (Total female population)'] + df_out['From 85 to 89 years (Total female population)'] + df_out['From 90 to 94 years (Total female population)'] + df_out['From 95 to 99 years (Total female population)']

df_out['6-8 persons'] = df_out['6 persons'] + df_out['7 persons'] + df_out['8 persons']
df_out['9+ persons'] = df_out['9 persons'] + df_out['10 persons'] + df_out['11 persons or more']

df_out['Students'] = df_out['Students (Total male population)'] + df_out['Students (Total female population)']
df_out['Employed'] = df_out['Employed (Total male population)'] + df_out['Employed (Total female population)']
df_out['Unemployed'] = df_out['Unemployed (Total male population)'] + df_out['Unemployed (Total female population)']
df_out['Pensioners or recipients'] = df_out['Pensioners or recipients of capital income (Total male population)'] + df_out['Pensioners or recipients of capital income (Total female population)']
df_out['Persons under the national minimum age for economic activity'] = df_out['Persons under the national minimum age for economic activity (Total male population)'] + df_out['Persons under the national minimum age for economic activity (Total female population)']

df_out['No diploma or certificate'] = df_out['No diploma or certificate (ISCED 0) (Total female population)'] + df_out['No diploma or certificate (ISCED 0) (Total male population)']
df_out['Primary education'] = df_out['Primary education (ISCED 1) (Total female population)'] + df_out['Primary education (ISCED 1) (Total male population)']
df_out['Lower secondary education'] = df_out['Lower secondary education (ISCED 2) (Total female population)'] + df_out['Lower secondary education (ISCED 2) (Total male population)']
df_out['Upper secondary education'] = df_out['Upper secondary education (ISCED 3) (Total female population)'] + df_out['Upper secondary education (ISCED 3) (Total male population)']
df_out['Post-secondary non tertiary education'] = df_out['Post-secondary non tertiary education (ISCED 4) (Total female population)'] + df_out['Post-secondary non tertiary education (ISCED 4) (Total male population)']
df_out['Short cycle Tertiary education'] = df_out['Short cycle Tertiary education (ISCED 5) (Total female population)'] + df_out['Short cycle Tertiary education (ISCED 5) (Total male population)']
df_out['Bachelors or equivalent'] = df_out['Bachelors or equivalent (ISCED 6) (Total female population)'] + df_out['Bachelors or equivalent (ISCED 6) (Total male population)']
df_out['Masters or equivalent'] = df_out['Masters or equivalent (ISCED 7) (Total female population)'] + df_out['Masters or equivalent (ISCED 7) (Total male population)']
df_out['Doctorate or equivalent'] = df_out['Doctorate or equivalent (ISCED 8) (Total female population)'] + df_out['Doctorate or equivalent (ISCED 8) (Total male population)']

In [44]:
column_not_used = [
    '6 persons', '7 persons', '8 persons', '9 persons', '10 persons', '11 persons or more',
    
    'From 20 to 24 years (Total female population)', 'From 20 to 24 years (Total male population)',
    'From 25 to 29 years (Total female population)', 'From 25 to 29 years (Total male population)',
    'From 30 to 34 years (Total female population)', 'From 30 to 34 years (Total male population)',
    'From 35 to 39 years (Total female population)', 'From 35 to 39 years (Total male population)',
    'From 40 to 44 years (Total female population)', 'From 40 to 44 years (Total male population)',
    'From 45 to 49 years (Total female population)', 'From 45 to 49 years (Total male population)',
    'From 50 to 54 years (Total female population)', 'From 50 to 54 years (Total male population)',
    'From 55 to 59 years (Total female population)', 'From 55 to 59 years (Total male population)',
    'From 60 to 64 years (Total female population)', 'From 60 to 64 years (Total male population)',
    'From 65 to 69 years (Total female population)', 'From 65 to 69 years (Total male population)',
    'From 70 to 74 years (Total female population)', 'From 70 to 74 years (Total male population)',
    'From 75 to 79 years (Total female population)', 'From 75 to 79 years (Total male population)',
    'From 80 to 84 years (Total female population)', 'From 80 to 84 years (Total male population)',
    'From 85 to 89 years (Total female population)', 'From 85 to 89 years (Total male population)',
    'From 90 to 94 years (Total female population)', 'From 90 to 94 years (Total male population)',
    'From 95 to 99 years (Total female population)', 'From 95 to 99 years (Total male population)',
    '100 years and older (Total female population)', '100 years and older (Total male population)',

    'No diploma or certificate (ISCED 0) (Total female population)', 'No diploma or certificate (ISCED 0) (Total male population)',
    'Primary education (ISCED 1) (Total female population)', 'Primary education (ISCED 1) (Total male population)',
    'Lower secondary education (ISCED 2) (Total female population)', 'Lower secondary education (ISCED 2) (Total male population)',
    'Upper secondary education (ISCED 3) (Total female population)', 'Upper secondary education (ISCED 3) (Total male population)',
    'Post-secondary non tertiary education (ISCED 4) (Total female population)', 'Post-secondary non tertiary education (ISCED 4) (Total male population)',
    'Short cycle Tertiary education (ISCED 5) (Total female population)', 'Short cycle Tertiary education (ISCED 5) (Total male population)',
    'Bachelors or equivalent (ISCED 6) (Total female population)', 'Bachelors or equivalent (ISCED 6) (Total male population)',
    'Masters or equivalent (ISCED 7) (Total female population)', 'Masters or equivalent (ISCED 7) (Total male population)',
    'Doctorate or equivalent (ISCED 8) (Total female population)', 'Doctorate or equivalent (ISCED 8) (Total male population)',
    
    'Not applicable (for persons younger than 15) (Total female population)', 'Not applicable (for persons younger than 15) (Total male population)',
    'Not specified (for persons 15 years or older) (Total female population)', 'Not specified (for persons 15 years or older) (Total male population)',
    'Others (Total female population)', 'Others (Total male population)',

    'Students (Total female population)', 'Students (Total male population)',
    'Employed (Total female population)', 'Employed (Total male population)',
    'Unemployed (Total female population)', 'Unemployed (Total male population)',
    'Pensioners or recipients of capital income (Total female population)', 'Pensioners or recipients of capital income (Total male population)',
    'Persons under the national minimum age for economic activity (Total female population)', 'Persons under the national minimum age for economic activity (Total male population)',
    ]

In [45]:
df_out = df_out.drop(columns=column_not_used)

In [46]:
df_out.shape

(19365, 41)

In [47]:
df_out

,area_id,1 person,2 persons,3 persons,4 persons,5 persons,From 10 to 14 years (Total female population),From 10 to 14 years (Total male population),From 15 to 19 years (Total female population),From 15 to 19 years (Total male population),From 5 to 9 years (Total female population),From 5 to 9 years (Total male population),Younger than 5 years (Total female population),Younger than 5 years (Total male population),total_male_population,total_female_population,total_population,20-34 (male),35-54 (male),55-69 (male),70+ (male),20-34 (female),35-54 (female),55-69 (female),70+ (female),6-8 persons,9+ persons,Students,Employed,Unemployed,Pensioners or recipients,Persons under the national minimum age for economic activity,No diploma or certificate,Primary education,Lower secondary education,Upper secondary education,Post-secondary non tertiary education,Short cycle Tertiary education,Bachelors or equivalent,Masters or equivalent,Doctorate or equivalent
0,1-6-11001A00-,414.0,426.0,143.0,117.0,38.0,57.0,73.0,50.0,62.0,53.0,55.0,51.0,59.0,1187.0,1260.0,2447.0,183.0,279.0,254.0,222.0,179.0,291.0,289.0,290.0,13.0,1.0,147.0,1040.0,49.0,729.0,348.0,27.0,202.0,418.0,655.0,83.0,50.0,370.0,199.0,14.0
1,1-6-11001A01-,298.0,466.0,168.0,173.0,53.0,85.0,78.0,84.0,89.0,90.0,88.0,43.0,71.0,1407.0,1409.0,2816.0,185.0,377.0,283.0,236.0,192.0,378.0,279.0,258.0,19.0,1.0,220.0,1240.0,66.0,703.0,455.0,30.0,143.0,376.0,777.0,94.0,51.0,488.0,296.0,22.0
2,1-6-11001A020,52.0,103.0,43.0,57.0,13.0,30.0,20.0,20.0,25.0,23.0,23.0,13.0,14.0,350.0,365.0,715.0,47.0,90.0,75.0,56.0,46.0,109.0,67.0,57.0,4.0,1.0,57.0,335.0,8.0,161.0,123.0,7.0,27.0,84.0,165.0,23.0,18.0,140.0,107.0,5.0
3,1-6-11001A030,42.0,75.0,22.0,26.0,7.0,16.0,10.0,6.0,9.0,14.0,20.0,17.0,11.0,225.0,211.0,436.0,50.0,69.0,38.0,18.0,50.0,47.0,39.0,22.0,6.0,0.0,24.0,217.0,10.0,70.0,88.0,2.0,30.0,62.0,124.0,14.0,13.0,53.0,26.0,1.0
4,1-6-11001A042,25.0,60.0,19.0,17.0,10.0,8.0,9.0,9.0,9.0,2.0,8.0,5.0,3.0,181.0,163.0,344.0,38.0,25.0,41.0,48.0,19.0,38.0,44.0,38.0,4.0,0.0,41.0,132.0,4.0,112.0,35.0,0.0,6.0,34.0,84.0,4.0,7.0,81.0,75.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19360,1-6-93090G191,5.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,16.0,14.0,30.0,4.0,3.0,5.0,3.0,2.0,1.0,5.0,3.0,1.0,0.0,2.0,10.0,2.0,8.0,4.0,2.0,5.0,4.0,6.0,0.0,0.0,5.0,4.0,0.0
19361,1-6-93090H000,47.0,29.0,14.0,12.0,7.0,12.0,9.0,9.0,3.0,11.0,8.0,6.0,4.0,108.0,141.0,249.0,15.0,32.0,24.0,13.0,21.0,35.0,28.0,19.0,3.0,0.0,13.0,97.0,13.0,50.0,50.0,3.0,20.0,43.0,68.0,3.0,0.0,41.0,14.0,0.0
19362,1-6-93090H012,4.0,10.0,5.0,6.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,0.0,36.0,37.0,73.0,7.0,10.0,7.0,5.0,5.0,9.0,6.0,7.0,0.0,0.0,4.0,34.0,0.0,19.0,13.0,2.0,7.0,10.0,19.0,1.0,0.0,13.0,6.0,0.0
19363,1-6-93090H063,5.0,5.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,13.0,10.0,23.0,2.0,4.0,3.0,4.0,0.0,1.0,3.0,3.0,0.0,0.0,1.0,10.0,0.0,9.0,2.0,2.0,0.0,10.0,3.0,0.0,0.0,2.0,3.0,0.0
19364,1-6-93090H091,7.0,1.0,2.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,18.0,9.0,27.0,1.0,6.0,4.0,3.0,2.0,4.0,2.0,0.0,0.0,0.0,1.0,13.0,0.0,6.0,5.0,1.0,1.0,3.0,11.0,1.0,0.0,1.0,2.0,1.0