In [15]:
import pandas as pd

In [33]:
# df1
poi_tabel = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'value': ['A', 'B', 'C', 'D', 'E']
})

# df2
poi_match_tabel = pd.DataFrame({
    'id': [9, 5, 4, 7, 8],
    'value': ['D', 'E', 'F', 'G', 'H']
})

In [34]:
poi_tabel

   id value
0   1     A
1   2     B
2   3     C
3   4     D
4   5     E

In [35]:
poi_match_tabel

   id value
0   9     D
1   5     E
2   4     F
3   7     G
4   8     H

In [36]:
poi_tabel_clean = poi_tabel[poi_tabel['id'].isin(poi_match_tabel['id'])].reset_index().drop('index', axis=1)
poi_match_tabel_clean = poi_match_tabel[poi_match_tabel['id'].isin(poi_tabel['id'])].reset_index().drop('index', axis=1)

In [37]:
poi_tabel_clean

   id value
0   4     D
1   5     E

In [41]:
poi_match_tabel_clean

   id value
0   5     E
1   4     F

filter de poi's weg met minder records dan 100?