In [ ]:
import pandas as pd

In [6]:
area_meta_df = pd.read_csv("area_meta_cleaned.csv")
poi_df = pd.read_csv("poi_matches_MLP_cleaned.csv")

dus in pois heb je een point.
in areas heb je een geom waarbinnen censusdata valt.
1) join areas met area_meta op basis van area_id om zo de kolom geom aan area_meta te geven
2) voor elke rij in in df_merged -> ga na welk punt in geom het dichtste bij point ligt van pois. Deze moet dichter liggen dan 5km van het punt. ga na welk punt in geom het verste van point ligt van pois. Deze moet dichter liggen dan 5.2km van het punt. alle rijen die hieraan voldoen worden bij elkaar opgetelt worden en bij die poi gezet.

In [ ]:
poi_df.shape

In [10]:
poi_df.head()

,date,poi_id,matches,month,day_name,is_weekend,Seizoen,point
0,2025-01-02,18699,5,januari,Thursday,0,herfst,POINT(4.702411389059087 50.99397698611658)
1,2025-01-04,18699,5,januari,Saturday,1,herfst,POINT(4.702411389059087 50.99397698611658)
2,2025-01-05,18699,5,januari,Sunday,1,herfst,POINT(4.702411389059087 50.99397698611658)
3,2025-01-06,18699,4,januari,Monday,0,herfst,POINT(4.702411389059087 50.99397698611658)
4,2025-01-07,18699,1,januari,Tuesday,0,herfst,POINT(4.702411389059087 50.99397698611658)

In [8]:
area_meta_df.head()

,area_id,geometry,1 person,2 persons,3 persons,4 persons,5 persons,From 10 to 14 years (Total female population),From 10 to 14 years (Total male population),From 15 to 19 years (Total female population),...,Persons under the national minimum age for economic activity,No diploma or certificate,Primary education,Lower secondary education,Upper secondary education,Post-secondary non tertiary education,Short cycle Tertiary education,Bachelors or equivalent,Masters or equivalent,Doctorate or equivalent
0,1-6-82032B00-,"POLYGON((5.95935985763697 50.3094619520165, 5....",26.0,42.0,17.0,23.0,8.0,5.0,9.0,8.0,...,68.0,5.0,24.0,48.0,73.0,9.0,0.0,65.0,12.0,0.0
1,1-6-82037B19-,"POLYGON((6.02712762297411 50.2098971823183, 6....",9.0,8.0,2.0,2.0,1.0,1.0,0.0,1.0,...,4.0,0.0,6.0,9.0,12.0,1.0,0.0,5.0,0.0,0.0
2,1-6-82037D00-,"POLYGON((5.85889815596349 50.1770549579093, 5....",14.0,16.0,10.0,10.0,2.0,1.0,5.0,3.0,...,25.0,2.0,7.0,17.0,37.0,4.0,0.0,22.0,10.0,1.0
3,1-6-83012A001,"POLYGON((5.45578148067834 50.3503693193278, 5....",20.0,6.0,2.0,4.0,2.0,1.0,0.0,4.0,...,7.0,0.0,5.0,12.0,20.0,1.0,0.0,13.0,4.0,0.0
4,1-6-83012E01-,"POLYGON((5.49576698834463 50.3519634152142, 5....",50.0,32.0,7.0,6.0,1.0,3.0,5.0,1.0,...,22.0,4.0,22.0,38.0,58.0,3.0,0.0,21.0,6.0,1.0